- name: install lua curl htop golang pip preload build-essential cmake
  apt:
    name:
      [
        "lua5.1",
        "curl",
        "htop",
        "golang",
        "python3-pip",
        "preload",
        "build-essential",
        "cmake",
        "pkg-config",
        "unzip",
        "libtool",
        "libtool-bin",
        "gettext",
      ]
  tags:
    - core
- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name:
      [
        "ccache",
        "ninja-build",
        "python3-pip",
        "dconf-editor",
        "moreutils",
        "clangd",
      ]
  tags:
    - core
