- name: shutter ppa (ppa:linuxuprising/shutter)
  become: true
  apt_repository:
    repo: ppa:linuxuprising/shutter
    state: present
    update_cache: True
  tags:
    - productivity

- name: Install packages
  become: true
  apt:
    name: ["tmux", "fzf", "tldr", "ripgrep", "shutter"]
  tags:
    - productivity
